name: PWA Automation Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Execute Automation Test
        run: yarn clean-test-dev
        env:
          CASDOOR: ${{ secrets.CASDOOR }}
          BASE_URL: ${{ secrets.BASE_URL }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SUPER_VISOR_USERNAME: ${{ secrets.SUPER_VISOR_USERNAME }}
          SUPER_VISOR_PASSWORD: ${{ secrets.SUPER_VISOR_PASSWORD }}
          EMPLOYEE_USERNAME: ${{ secrets.EMPLOYEE_USERNAME }}
          EMPLOYEE_PASSWORD: ${{ secrets.EMPLOYEE_PASSWORD }}

      - name: Render allure report
        run: yarn allure-render
        if: always()

      - name: Upload test report as artifact. To troubleshoot failures, extract .zip and investigate.
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/

      - name: 'Publish test results'
        uses: peaceiris/actions-gh-pages@v3.9.3
        if: always()
        with:
          publish_branch: allure
          github_token: ${{ secrets.MILANA_ALLURE }}
          publish_dir: milana-rendered-allure/
          keep_files: true
